version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    container_name: test-future-app
    restart: always
    working_dir: /var/www/
  nginx:
    image: nginx:alpine
    container_name: test-future-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
  db:
    image: mysql/mysql-server:8.0
    container_name: test-future-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: future_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-db:/var/lib/mysql

volumes:
  mysql-db: